import { Link } from "react-router-dom";
import { motion } from "framer-motion";

const Footer = () => {
  return (
    <footer className="relative border-t border-white/5 bg-oil-dark/50">
      {/* Gradient line at top */}
      <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-oil-gold/30 to-transparent" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 lg:px-10 py-12">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
          {/* Brand */}
          <div>
            <div className="flex items-center gap-3 mb-4">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-oil-gold to-oil-amber flex items-center justify-center">
                <span className="text-oil-black font-bold text-sm font-display">
                  O
                </span>
              </div>
              <span className="text-lg font-bold font-display text-gradient-gold">
                PetroCast
              </span>
            </div>
            <p className="text-gray-500 text-sm leading-relaxed max-w-xs">
              AI-powered crude oil price forecasting platform. Built for
              critical decision-making.
            </p>
          </div>

          {/* Quick Links */}
          <div>
            <h4 className="text-sm font-semibold text-gray-300 uppercase tracking-wider mb-4">
              Quick Links
            </h4>
            <div className="flex flex-col gap-2.5">
              {[
                { label: "Home", path: "/" },
                { label: "Dashboard", path: "/dashboard" },
                { label: "Methodology", path: "/about" },
              ].map((link) => (
                <Link
                  key={link.path}
                  to={link.path}
                  className="text-gray-500 hover:text-oil-gold text-sm transition-colors w-fit"
                >
                  {link.label}
                </Link>
              ))}
            </div>
          </div>

          {/* Disclaimer */}
          <div>
            <h4 className="text-sm font-semibold text-gray-300 uppercase tracking-wider mb-4">
              Disclaimer
            </h4>
            <p className="text-gray-600 text-xs leading-relaxed">
              Price forecasts are generated by machine learning models and
              should not be used as the sole basis for financial decisions. Past
              performance does not guarantee future results. This tool is for
              research and educational purposes.
            </p>
          </div>
        </div>

        {/* Bottom Bar */}
        <div className="mt-10 pt-6 border-t border-white/5 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-gray-600 text-xs">
            © 2026 PetroCast · Final Year Research Project
          </p>
          <div className="flex items-center gap-2">
            <motion.div
              animate={{ scale: [1, 1.2, 1] }}
              transition={{ duration: 2, repeat: Infinity }}
              className="w-2 h-2 rounded-full bg-oil-green"
            />
            <span className="text-xs text-gray-500">Models Active</span>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
